services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: furia-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    networks:
      - furia_net

  redis:
    image: redis/redis-stack:latest
    container_name: furia-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - furia_net

networks:
  furia_net:
    driver: bridge
